### PR TITLE
Update to recent frameworks and dependencies versions

### PR DESCRIPTION
**Pull request by jclaveau**
Only one warning remains due to semantic versioning error done by class-transformers developers:
"@nestjs/graphql > @nestjs/mapped-types@1.0.0" has incorrect peer dependency "class-transformer@^0.2.0 || ^0.3.0 || ^0.4.0"

To simplify dependency management, I personally use Renovate with auto-merging updates of all minor ones if only tests do not fail. Here is my configuration file https://github.com/jclaveau/nestjs-experiments/blob/main/renovate.json5

It saves a lot of time :)

Thanks a lot for your work!

### CODE REVIEW

**Comment by thisismydesign** [comment]
@jclaveau Much appreciated, thank you! Could you enable actions on your fork so the CI can run? I'm surprised that it didn't run here, I will look into solving that later.

**Comment by jclaveau** [comment]
I have issues with Next's build process do you have any clue?

**Comment by thisismydesign** [comment]
@jclaveau `yarn build` does `NODE_ENV=production nest build && cd src/client && next build`. Perhaps it's an issue with the next build?

**Comment by thisismydesign** [comment]
Checked the [upgrade guides](https://nextjs.org/docs/upgrading) from v10 up to v12, didn't see anything obvious. Another place `src/client` is specified is in `.eslintrc.js`. Don't think this should affect the build but perhaps it's worth looking at it.

**Comment by thisismydesign** [comment]
Thanks @jclaveau! Looks like this was introduced in v11 of Next, so you could still update until v10 and the rest of the updates would be fine to merge as well.

**Comment by thisismydesign** [comment]
Closing, automated dependency updates are added in https://github.com/thisismydesign/nestjs-starter/issues/26

**Comment by thisismydesign** [comment]
Updated most dependencies to latest versions and resolved issues. Next.js was updated in https://github.com/thisismydesign/nestjs-starter/pull/81

@jclaveau FYI I worked around the ESLint issue by disabling it in the build step, we're running a separate ESLint config anyways. Created a follow-up issue though, I think it's possible to solve it with a bit of digging: https://github.com/thisismydesign/nestjs-starter/issues/82

**Comment by thisismydesign** [comment]
And finally fixed the build by https://github.com/thisismydesign/nestjs-starter/pull/83

**Pull request closed without merging**
